### ISSUE TITLE
Duplicated hits

### ISSUE THREAD

**Issue by alfredoivan** [combogenomics/CONTIGuator#12]
Hello. I am a regular user of the soft. I found an non-critical issue (i think) with duplicated hits.
The program would mark a contig as containing only duplicated hits. I don't believe this is true, but bypassing it would let me increase my genome coverage in a part where there were no contigs hitting.

(i can submit example files and/or prints of the pdf output so you can see)

Would you add an option to ignore "only duplicated hits" from excluding contigs?

Greetings,
Alfredo.

**Comment by mgalardini** [comment]
Hi Alfredo,

I went again through the bits of the code that check for the presence of duplicated hits; it should discard those contigs only if they contain duplicated hits and no "unique hits". There still could be a bug or something like that, so feel free to send me your files or your pdf map for further inspection.

Marco

**Comment by alfredoivan** [comment]
OK thanks.
